// 全局的mutations-type类型
export const SAVE_TOGGLE_SYSTEM = 'SAVE_TOGGLE_SYSTEM';

export const SAVE_USERINFO = 'SAVE_USERINFO';

export const SAVE_LOGOUT = 'SAVE_LOGOUT';

export const SAVE_SYSTEM_INFO = 'SAVE_SYSTEM_INFO';

export const SAVE_COMPANY_STAFF_INFO = 'SAVE_COMPANY_STAFF_INFO';

export const SAVE_COMPANY_LIST_INFO = 'SAVE_COMPANY_LIST_INFO';

export const TOGGLE_LOADING = 'TOGGLE_LOADING';

export const SAVE_DEPARTMENT_LIST = 'SAVE_DEPARTMENT_LIST';

export const SAVE_STAFF_INFO_DETAIL = 'SAVE_STAFF_INFO_DETAIL';

export const SAVE_POST_LIST = 'SAVE_POST_LIST';

export const SAVE_COMPANYID = 'SAVE_COMPANYID';

export const SAVE_ROLE_LIST = 'SAVE_ROLE_LIST';

export const SAVE_SYSTEM_FOF_COMPANY = 'SAVE_SYSTEM_FOF_COMPANY';

export const SAVE_CONSOLE_RESOURCE = 'SAVE_CONSOLE_RESOURCE';

export const SAVE_ROLEID = 'SAVE_ROLEID';
